### PR TITLE
Fix popups disappearing

### LINKED ISSUE #26: Fix 'Log not found' popup after v0.12.1
After releasing v0.12.1 some users report an absence of the popup notification balloon informing that selected log cannot be found. No errors in AnaLog's own log are observed.
This makes the application's behavior ambiguous: it's not clear if a log is not found or AnaLog is just loading it.
The bug was reproduced at least on Windows and Linux platforms.

### PR DESCRIPTION
**Pull request by Toparvion**
Fixes #26 .

Changes summary:
- Do not rely on the result of endpoints' `toString()` method anymore
- Instead, use `ContainerTargetFile` as the provider of information about event source
- Fix log levels in `LocalizedLogger`

### CODE REVIEW

**Comment by Toparvion** [comment]
The problem was in `TailEventHandler#processFileTailingEvent` method, which used to extract the event source's log path from `toString()` method of the corresponding bean (please don't ask me why 😄). From now on it uses `ContainerTargetFile#getAbsolutePath` method whose result is controlled by our preceding logic (for example see `TailingFlowProvider#newTailAdapter4Docker` method) and thus should be protected from changes in upcoming versions of frameworks.

**Review by a-polyudov — APPROVED** [review]

**Comment by Toparvion** [comment]
I asked our teammates to check the fix in their AnaLog deployment. Will proceed with this PR when they reply.

**Comment by Toparvion** [comment]
Out teammates reported they don't see any changes to the popups' behavior. Will investigate it further...

**Comment by Toparvion** [comment]
Found the source of the reported problem and fixed it. Waiting for the feedback again.

**Comment by Toparvion** [comment]
So, I've finally fixed the problem and eventually added unit tests to the `TailEventHandler` (thanks to SonarCloud that forced me to do it). 
This issue appeared to be not so simple as it seemed at the beginning. Nonetheless we've fixed it. Another good experience 🙂

**Pull request merged**
